---
title: "Script"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(foreign)
```

```{r}
brfss_2012 <- read.xport("data/LLCP2012.XPT", as.is=TRUE)
brfss_2013 <- read.xport("data/LLCP2013.XPT", as.is=TRUE)
brfss_2014 <- read.xport("data/LLCP2014.XPT")
brfss_2015 <- read.xport("data/LLCP2015.XPT")
brfss_2016 <- read.xport("data/LLCP2016.XPT")
brfss_2017 <- read.xport("data/LLCP2017.XPT")
brfss_2018 <- read.xport("data/LLCP2018.XPT")
brfss_2019 <- read.xport("data/LLCP2019.XPT")
```

```{r}
unique(brfss_2013[c("X_STATE")])
```


```{r}
names(brfss_2013)[names(brfss_2013) == "iyear"] <- "IYEAR"
names(brfss_2013)[names(brfss_2013) == "X_state"] <- "X_STATE"
names(brfss_2013)[names(brfss_2013) == "numadult"] <- "NUMADULT"
names(brfss_2013)[names(brfss_2013) == "menthlth"] <- "MENTHLTH"
names(brfss_2013)[names(brfss_2013) == "poorhlth"] <- "POORHLTH"
names(brfss_2013)[names(brfss_2013) == "marital"] <- "MARITAL"
names(brfss_2013)[names(brfss_2013) == "children"] <- "CHILDREN"
names(brfss_2013)[names(brfss_2013) == "educa"] <- "EDUCA"
names(brfss_2013)[names(brfss_2013) == "employ1"] <- "EMPLOY1"
names(brfss_2013)[names(brfss_2013) == "income2"] <- "INCOME2"
names(brfss_2013)[names(brfss_2013) == "veteran3"] <- "VETERAN3"
names(brfss_2013)[names(brfss_2013) == "renthom1"] <- "RENTHOM1"
names(brfss_2013)[names(brfss_2013) == "sex"] <- "SEX"
names(brfss_2013)[names(brfss_2013) == "pregnant"] <- "PREGNANT"
names(brfss_2013)[names(brfss_2013) == "X_ageg5yr"] <- "X_AGEG5YR"
names(brfss_2013)[names(brfss_2013) == "X_age65yr"] <- "X_AGE65YR"
names(brfss_2013)[names(brfss_2013) == "X_age_g"] <- "X_AGE_G"
names(brfss_2013)[names(brfss_2013) == "X_chldcnt"] <- "X_CHLDCNT"
names(brfss_2013)[names(brfss_2013) == "X_educag"] <- "X_EDUCAG"
names(brfss_2013)[names(brfss_2013) == "X_incomg"] <- "X_INCOMG"
names(brfss_2013)[names(brfss_2013) == "smoke100"] <- "SMOKE100"
names(brfss_2013)[names(brfss_2013) == "smokday2"] <- "SMOKDAY2"
names(brfss_2013)[names(brfss_2013) == "lastsmk2"] <- "LASTSMK2"
names(brfss_2013)[names(brfss_2013) == "stopsmk2"] <- "STOPSMK2"
names(brfss_2013)[names(brfss_2013) == "usenow3"] <- "USENOW3"
names(brfss_2013)[names(brfss_2013) == "X_smoker3"] <- "X_SMOKER3"
names(brfss_2013)[names(brfss_2013) == "X_rfsmok3"] <- "X_RFSMOK3"
names(brfss_2013)[names(brfss_2013) == "qlmentl2"] <- "QLMENTL2"
names(brfss_2013)[names(brfss_2013) == "qlstres2"] <- "QLSTRES2"
names(brfss_2013)[names(brfss_2013) == "qlstres2"] <- "QLSTRES2"
names(brfss_2013)[names(brfss_2013) == "emtsuprt"] <- "EMTSUPRT"
names(brfss_2013)[names(brfss_2013) == "addepev2"] <- "ADDEPEV2"

names(brfss_2018)[names(brfss_2018) == "SEX1"] <- "SEX"

names(brfss_2019)[names(brfss_2019) == "SEXVAR"] <- "SEX"
names(brfss_2019)[names(brfss_2019) == "ADDEPEV3"] <- "ADDEPEV2"
```

```{r}
data2013 <- subset(brfss_2013, select=c("IYEAR", "X_STATE", "NUMADULT", 
                                          "MENTHLTH", "POORHLTH", "MARITAL", 
                                          "CHILDREN", "EDUCA", "EMPLOY1",
                                          "INCOME2", "VETERAN3", "RENTHOM1",
                                          "SEX", "PREGNANT", "X_AGEG5YR",
                                          "X_AGE65YR", "X_AGE_G", "X_CHLDCNT",
                                          "X_EDUCAG", "X_INCOMG", "SMOKE100",
                                          "SMOKDAY2", "LASTSMK2", "STOPSMK2",
                                         "USENOW3", "X_SMOKER3", "X_RFSMOK3",
                                         "QLMENTL2", "QLSTRES2", "EMTSUPRT",
                                         "LSATISFY", "ADDEPEV2"))
```

```{r}
data2014 <- subset(brfss_2014, select=c("IYEAR", "X_STATE", "NUMADULT", 
                                          "MENTHLTH", "POORHLTH", "MARITAL", 
                                          "CHILDREN", "EDUCA", "EMPLOY1",
                                          "INCOME2", "VETERAN3", "RENTHOM1",
                                          "SEX", "PREGNANT", "X_AGEG5YR",
                                          "X_AGE65YR", "X_AGE_G", "X_CHLDCNT",
                                          "X_EDUCAG", "X_INCOMG", "SMOKE100",
                                          "SMOKDAY2", "LASTSMK2", "STOPSMK2",
                                         "USENOW3", "X_SMOKER3", "X_RFSMOK3",
                                         "QLMENTL2", "QLSTRES2", "EMTSUPRT",
                                         "LSATISFY", "ADDEPEV2"))
```

```{r}
data2015 <- subset(brfss_2015, select=c("IYEAR", "X_STATE", "NUMADULT", 
                                          "MENTHLTH", "POORHLTH", "MARITAL", 
                                          "CHILDREN", "EDUCA", "EMPLOY1",
                                          "INCOME2", "VETERAN3", "RENTHOM1",
                                          "SEX", "PREGNANT", "X_AGEG5YR",
                                          "X_AGE65YR", "X_AGE_G", "X_CHLDCNT",
                                          "X_EDUCAG", "X_INCOMG", "SMOKE100",
                                          "SMOKDAY2", "LASTSMK2", "STOPSMK2",
                                         "USENOW3", "X_SMOKER3", "X_RFSMOK3",
                                         "QLMENTL2", "QLSTRES2", "EMTSUPRT",
                                         "LSATISFY", "ADDEPEV2"))
```

```{r}
data2016 <- subset(brfss_2016, select=c("IYEAR", "X_STATE", "NUMADULT", 
                                          "MENTHLTH", "POORHLTH", "MARITAL", 
                                          "CHILDREN", "EDUCA", "EMPLOY1",
                                          "INCOME2", "VETERAN3", "RENTHOM1",
                                          "SEX", "PREGNANT", "X_AGEG5YR",
                                          "X_AGE65YR", "X_AGE_G", "X_CHLDCNT",
                                          "X_EDUCAG", "X_INCOMG", "SMOKE100",
                                          "SMOKDAY2", "LASTSMK2", "STOPSMK2",
                                         "USENOW3", "X_SMOKER3", "X_RFSMOK3",
                                         "QLMENTL2", "QLSTRES2", "EMTSUPRT",
                                         "LSATISFY", "ADDEPEV2"))
```

```{r}
data2017 <- subset(brfss_2017, select=c("IYEAR", "X_STATE", "NUMADULT", 
                                          "MENTHLTH", "POORHLTH", "MARITAL", 
                                          "CHILDREN", "EDUCA", "EMPLOY1",
                                          "INCOME2", "VETERAN3", "RENTHOM1",
                                          "SEX", "PREGNANT", "X_AGEG5YR",
                                          "X_AGE65YR", "X_AGE_G", "X_CHLDCNT",
                                          "X_EDUCAG", "X_INCOMG", "SMOKE100",
                                          "SMOKDAY2", "LASTSMK2", "STOPSMK2",
                                         "USENOW3", "X_SMOKER3", "X_RFSMOK3",
                                         "QLMENTL2", "QLSTRES2", "EMTSUPRT",
                                         "LSATISFY", "ADDEPEV2"))
```

```{r}
data2018 <- subset(brfss_2018, select=c("IYEAR", "X_STATE", "NUMADULT", 
                                          "MENTHLTH", "POORHLTH", "MARITAL", 
                                          "CHILDREN", "EDUCA", "EMPLOY1",
                                          "INCOME2", "VETERAN3", "RENTHOM1",
                                          "SEX", "PREGNANT", "X_AGEG5YR",
                                          "X_AGE65YR", "X_AGE_G", "X_CHLDCNT",
                                          "X_EDUCAG", "X_INCOMG", "SMOKE100",
                                          "SMOKDAY2", "LASTSMK2", "STOPSMK2",
                                          "USENOW3", "X_SMOKER3", "X_RFSMOK3",
                                          "ADDEPEV2"))
```

```{r}
data2019 <- subset(brfss_2019, select=c("IYEAR", "X_STATE", "NUMADULT", 
                                          "MENTHLTH", "POORHLTH", "MARITAL", 
                                          "CHILDREN", "EDUCA", "EMPLOY1",
                                          "INCOME2", "VETERAN3", "RENTHOM1",
                                          "SEX", "PREGNANT", "X_AGEG5YR",
                                          "X_AGE65YR", "X_AGE_G", "X_CHLDCNT",
                                          "X_EDUCAG", "X_INCOMG", "SMOKE100",
                                          "SMOKDAY2", "LASTSMK2", "STOPSMK2",
                                          "USENOW3", "X_SMOKER3", "X_RFSMOK3", "ADDEPEV2"))
```

```{r}
data_2013_2014 <- Reduce(function(x, y) merge(x, y, all=TRUE), list(data2013, data2014))

data_2015_2016 <- Reduce(function(x, y) merge(x, y, all=TRUE), list(data2015, data2016))

data_2013_2016 <- Reduce(function(x, y) merge(x, y, all=TRUE), list(data_2013_2014, data_2015_2016))

data_2013_2017 <- Reduce(function(x, y) merge(x, y, all=TRUE), list(data_2013_2016, data2017))

data_2013_2019 <- Reduce(function(x, y) merge(x, y, all=TRUE), list(data_2013_2017, data2018, data2019))
```

```{r}
tobacco_mentalhealth <- subset(data_2013_2019, select=c("X_STATE","IYEAR","SMOKE100","SMOKDAY2",
                                                        "STOPSMK2","LASTSMK2","USENOW3","X_SMOKER3",
                                                        "X_RFSMOK3","POORHLTH",
                                                        "MENTHLTH", "QLMENTL2", "QLSTRES2", "ADDEPEV2",
                                                        "EMTSUPRT", "LSATISFY"))
```

```{r}
tobacco_sociodemo <- subset(data_2013_2019, select = c("SMOKE100","SMOKDAY2","STOPSMK2",
                                                    "LASTSMK2","USENOW3","X_SMOKER3", "X_RFSMOK3",
                                                    "X_STATE", "IYEAR", "NUMADULT", "VETERAN3", 
                                                    "MARITAL", "CHILDREN", "EDUCA", "EMPLOY1",
                                                    "INCOME2", "RENTHOM1", "SEX", "PREGNANT",
                                                    "X_AGEG5YR", "X_AGE65YR", "X_AGE_G", "X_CHLDCNT",
                                                    "X_EDUCAG", "X_INCOMG"))
```

```{r}
write.csv(data_2013_2019, paste("~/CNAM/Stats/Mini-memoire/data/", 'data_2013_2019.csv',sep = ''))
write.csv(tobacco_mentalhealth, paste("~/CNAM/Stats/Mini-memoire/data/", 'tobacco_mentalhealth.csv',sep = ''))
write.csv(tobacco_sociodemo, paste("~/CNAM/Stats/Mini-memoire/data/", 'tobacco_sociodemo.csv',sep = ''))
```
