---
title: "Tabagisme"
subtitle: "Analyse multivariee"
author: "Meyssa Beddar & Félita Donor"
output: 
  ioslides_presentation : 
    smaller: TRUE
runtime: shiny
---

### f
```{r}

fluidRow(
  column(4,
    "4"
  ),
  column(4, offset = 4,
    "4 offset 4"
  )      
)
fluidRow(
  column(3, offset = 3,
    "3 offset 3"
  ),
  column(3, offset = 3,
    "3 offset 3"
  )  
)

```

```{r eval=FALSE}
fluidPage(
  fluidRow(
    column(4,
      "4"
    ),
    column(4, offset = 4,
      "4 offset 4"
    )      
  ),
  fluidRow(
    column(3, offset = 3,
      "3 offset 3"
    ),
    column(3, offset = 3,
      "3 offset 3"
    )  
  )
)
```
```{r eval=FALSE}
fluidPage(
  fluidRow(
    column(4,
      "4"
    ),
    column(4, offset = 4,
      "4 offset 4"
    )      
  ),
  fluidRow(
    column(3, offset = 3,
      "3 offset 3"
    ),
    column(3, offset = 3,
      "3 offset 3"
    )  
  )
)
```
```{r eval=FALSE}
fluidPage(
  fluidRow(
    column(4,
      "4"
    ),
    column(4, offset = 4,
      "4 offset 4"
    )      
  ),
  fluidRow(
    column(3, offset = 3,
      "3 offset 3"
    ),
    column(3, offset = 3,
      "3 offset 3"
    )  
  )
)
```
