---
title: "R Notebook"
output: html_notebook
---
```{r load-packages, message = FALSE}
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(stargazer)
```


```{r fig.width = 7, fig.height = 7, dpi = 96}
visualize(
  data, 
  xvar = "X_SMOKER3", 
  type = "dist", 
  theme = "theme_minimal", 
  custom = FALSE
)
```

```{r fig.width = 7, fig.height = 7, dpi = 96}
visualize(
  data, 
  xvar = "X_RFSMOK3", 
  type = "dist", 
  fill = "SEX", 
  theme = "theme_minimal", 
  custom = FALSE
)
```

```{r fig.width = 7, fig.height = 7, dpi = 96}
visualize(
  data, 
  xvar = "STOPSMK2", 
  type = "dist", 
  theme = "theme_minimal", 
  custom = FALSE
)
```

```{r fig.width = 7, fig.height = 7, dpi = 96}
visualize(
  data, 
  xvar = "SMOKDAY2", 
  type = "dist", 
  theme = "theme_minimal", 
  custom = FALSE
)
```

```{r fig.width = 7, fig.height = 7, dpi = 96}
visualize(
  data, 
  xvar = "X_AGE65YR", 
  yvar = "X_RFSMOK3", 
  type = "bar", 
  fun = "n_obs", 
  theme = "theme_minimal", 
  custom = FALSE
)
```
