---
title: "Nettoyage"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(foreign)
library(naniar)
library(tidyverse)
```

## MERGE, RENAME, SELECT RELEVANT COLUMNS

```{r}
brfss_2013 <- read.xport("~/CNAM/Stats/Mini-memoire/data/LLCP2013.XPT")
brfss_2014 <- read.xport("~/CNAM/Stats/Mini-memoire/data/LLCP2014.XPT")
brfss_2015 <- read.xport("~/CNAM/Stats/Mini-memoire/data/LLCP2015.XPT")
brfss_2016 <- read.xport("~/CNAM/Stats/Mini-memoire/data/LLCP2016.XPT")
brfss_2017 <- read.xport("~/CNAM/Stats/Mini-memoire/data/LLCP2017.XPT")
brfss_2018 <- read.xport("~/CNAM/Stats/Mini-memoire/data/LLCP2018.XPT")
brfss_2019 <- read.xport("~/CNAM/Stats/Mini-memoire/data/LLCP2019.XPT")
```

```{r}
names(brfss_2013)[names(brfss_2013) == "iyear"] <- "IYEAR"
names(brfss_2013)[names(brfss_2013) == "X_state"] <- "X_STATE"
names(brfss_2013)[names(brfss_2013) == "numadult"] <- "NUMADULT"
names(brfss_2013)[names(brfss_2013) == "menthlth"] <- "MENTHLTH"
names(brfss_2013)[names(brfss_2013) == "poorhlth"] <- "POORHLTH"
names(brfss_2013)[names(brfss_2013) == "marital"] <- "MARITAL"
names(brfss_2013)[names(brfss_2013) == "children"] <- "CHILDREN"
names(brfss_2013)[names(brfss_2013) == "educa"] <- "EDUCA"
names(brfss_2013)[names(brfss_2013) == "employ1"] <- "EMPLOY1"
names(brfss_2013)[names(brfss_2013) == "income2"] <- "INCOME2"
names(brfss_2013)[names(brfss_2013) == "veteran3"] <- "VETERAN3"
names(brfss_2013)[names(brfss_2013) == "renthom1"] <- "RENTHOM1"
names(brfss_2013)[names(brfss_2013) == "sex"] <- "SEX"
names(brfss_2013)[names(brfss_2013) == "pregnant"] <- "PREGNANT"
names(brfss_2013)[names(brfss_2013) == "X_ageg5yr"] <- "X_AGEG5YR"
names(brfss_2013)[names(brfss_2013) == "X_age65yr"] <- "X_AGE65YR"
names(brfss_2013)[names(brfss_2013) == "X_age_g"] <- "X_AGE_G"
names(brfss_2013)[names(brfss_2013) == "X_chldcnt"] <- "X_CHLDCNT"
names(brfss_2013)[names(brfss_2013) == "X_educag"] <- "X_EDUCAG"
names(brfss_2013)[names(brfss_2013) == "X_incomg"] <- "X_INCOMG"
names(brfss_2013)[names(brfss_2013) == "smoke100"] <- "SMOKE100"
names(brfss_2013)[names(brfss_2013) == "smokday2"] <- "SMOKDAY2"
names(brfss_2013)[names(brfss_2013) == "lastsmk2"] <- "LASTSMK2"
names(brfss_2013)[names(brfss_2013) == "stopsmk2"] <- "STOPSMK2"
names(brfss_2013)[names(brfss_2013) == "usenow3"] <- "USENOW3"
names(brfss_2013)[names(brfss_2013) == "X_smoker3"] <- "X_SMOKER3"
names(brfss_2013)[names(brfss_2013) == "X_rfsmok3"] <- "X_RFSMOK3"
names(brfss_2013)[names(brfss_2013) == "qlmentl2"] <- "QLMENTL2"
names(brfss_2013)[names(brfss_2013) == "qlstres2"] <- "QLSTRES2"
names(brfss_2013)[names(brfss_2013) == "emtsuprt"] <- "EMTSUPRT"
names(brfss_2013)[names(brfss_2013) == "addepev2"] <- "ADDEPEV2"

names(brfss_2018)[names(brfss_2018) == "SEX1"] <- "SEX"

names(brfss_2019)[names(brfss_2019) == "SEXVAR"] <- "SEX"
names(brfss_2019)[names(brfss_2019) == "ADDEPEV3"] <- "ADDEPEV2"
```

```{r}
cols <- c("IYEAR", "IMONTH", "IDAY", "X_STATE", "NUMADULT", 
                                          "MENTHLTH", "POORHLTH", "MARITAL", 
                                          "CHILDREN", "EDUCA", "EMPLOY1",
                                          "INCOME2", "VETERAN3", "RENTHOM1",
                                          "SEX", "PREGNANT", "X_AGEG5YR",
                                          "X_AGE65YR", "X_AGE_G", "X_CHLDCNT",
                                          "X_EDUCAG", "X_INCOMG", "SMOKE100",
                                          "SMOKDAY2", "LASTSMK2", "STOPSMK2",
                                         "USENOW3", "X_SMOKER3", "X_RFSMOK3",
                                         "QLMENTL2", "QLSTRES2", "EMTSUPRT",
                                         "LSATISFY", "ADDEPEV2")
```


```{r}
data2013 <- subset(brfss_2013, select=c("IYEAR", "IMONTH", "IDAY", "X_STATE", "NUMADULT", 
                                          "MENTHLTH", "POORHLTH", "MARITAL", 
                                          "CHILDREN", "EDUCA", "EMPLOY1",
                                          "INCOME2", "VETERAN3", "RENTHOM1",
                                          "SEX", "PREGNANT", "X_AGEG5YR",
                                          "X_AGE65YR", "X_AGE_G", "X_CHLDCNT",
                                          "X_EDUCAG", "X_INCOMG", "SMOKE100",
                                          "SMOKDAY2", "LASTSMK2", "STOPSMK2",
                                         "USENOW3", "X_SMOKER3", "X_RFSMOK3",
                                         "QLMENTL2", "QLSTRES2", "EMTSUPRT",
                                         "LSATISFY", "ADDEPEV2"))
```

```{r}
data2014 <- subset(brfss_2014, select=c("IYEAR", "IMONTH", "IDAY", "X_STATE", "NUMADULT", 
                                          "MENTHLTH", "POORHLTH", "MARITAL", 
                                          "CHILDREN", "EDUCA", "EMPLOY1",
                                          "INCOME2", "VETERAN3", "RENTHOM1",
                                          "SEX", "PREGNANT", "X_AGEG5YR",
                                          "X_AGE65YR", "X_AGE_G", "X_CHLDCNT",
                                          "X_EDUCAG", "X_INCOMG", "SMOKE100",
                                          "SMOKDAY2", "LASTSMK2", "STOPSMK2",
                                         "USENOW3", "X_SMOKER3", "X_RFSMOK3",
                                         "QLMENTL2", "QLSTRES2", "EMTSUPRT",
                                         "LSATISFY", "ADDEPEV2"))
```

```{r}
data2015 <- subset(brfss_2015, select=c("IYEAR", "IMONTH", "IDAY",  "X_STATE", "NUMADULT", 
                                          "MENTHLTH", "POORHLTH", "MARITAL", 
                                          "CHILDREN", "EDUCA", "EMPLOY1",
                                          "INCOME2", "VETERAN3", "RENTHOM1",
                                          "SEX", "PREGNANT", "X_AGEG5YR",
                                          "X_AGE65YR", "X_AGE_G", "X_CHLDCNT",
                                          "X_EDUCAG", "X_INCOMG", "SMOKE100",
                                          "SMOKDAY2", "LASTSMK2", "STOPSMK2",
                                         "USENOW3", "X_SMOKER3", "X_RFSMOK3",
                                         "QLMENTL2", "QLSTRES2", "EMTSUPRT",
                                         "LSATISFY", "ADDEPEV2"))
```

```{r}
data2016 <- subset(brfss_2016, select=c("IYEAR", "IMONTH", "IDAY",  "X_STATE", "NUMADULT", 
                                          "MENTHLTH", "POORHLTH", "MARITAL", 
                                          "CHILDREN", "EDUCA", "EMPLOY1",
                                          "INCOME2", "VETERAN3", "RENTHOM1",
                                          "SEX", "PREGNANT", "X_AGEG5YR",
                                          "X_AGE65YR", "X_AGE_G", "X_CHLDCNT",
                                          "X_EDUCAG", "X_INCOMG", "SMOKE100",
                                          "SMOKDAY2", "LASTSMK2", "STOPSMK2",
                                         "USENOW3", "X_SMOKER3", "X_RFSMOK3",
                                         "QLMENTL2", "QLSTRES2", "EMTSUPRT",
                                         "LSATISFY", "ADDEPEV2"))
```

```{r}
data2017 <- subset(brfss_2017, select=c("IYEAR",  "IMONTH", "IDAY", "X_STATE", "NUMADULT", 
                                          "MENTHLTH", "POORHLTH", "MARITAL", 
                                          "CHILDREN", "EDUCA", "EMPLOY1",
                                          "INCOME2", "VETERAN3", "RENTHOM1",
                                          "SEX", "PREGNANT", "X_AGEG5YR",
                                          "X_AGE65YR", "X_AGE_G", "X_CHLDCNT",
                                          "X_EDUCAG", "X_INCOMG", "SMOKE100",
                                          "SMOKDAY2", "LASTSMK2", "STOPSMK2",
                                         "USENOW3", "X_SMOKER3", "X_RFSMOK3",
                                         "QLMENTL2", "QLSTRES2", "EMTSUPRT",
                                         "LSATISFY", "ADDEPEV2"))
```

```{r}
data2018 <- subset(brfss_2018, select=c("IYEAR",  "IMONTH", "IDAY", "X_STATE", "NUMADULT", 
                                          "MENTHLTH", "POORHLTH", "MARITAL", 
                                          "CHILDREN", "EDUCA", "EMPLOY1",
                                          "INCOME2", "VETERAN3", "RENTHOM1",
                                          "SEX", "PREGNANT", "X_AGEG5YR",
                                          "X_AGE65YR", "X_AGE_G", "X_CHLDCNT",
                                          "X_EDUCAG", "X_INCOMG", "SMOKE100",
                                          "SMOKDAY2", "LASTSMK2", "STOPSMK2",
                                         "USENOW3", "X_SMOKER3", "X_RFSMOK3","ADDEPEV2"))
```

```{r}
data2019 <- subset(brfss_2019, select=c("IYEAR","IMONTH", "IDAY", "X_STATE", "NUMADULT", 
                                          "MENTHLTH", "POORHLTH", "MARITAL", 
                                          "CHILDREN", "EDUCA", "EMPLOY1",
                                          "INCOME2", "VETERAN3", "RENTHOM1",
                                          "SEX", "PREGNANT", "X_AGEG5YR",
                                          "X_AGE65YR", "X_AGE_G", "X_CHLDCNT",
                                          "X_EDUCAG", "X_INCOMG", "SMOKE100",
                                          "SMOKDAY2", "LASTSMK2", "STOPSMK2",
                                          "USENOW3", "X_SMOKER3", "X_RFSMOK3", "ADDEPEV2"))
```

```{r}
data_2013_2014 <- Reduce(function(x, y) merge(x, y, all=TRUE), list(data2013, data2014))
data_2015_2016 <- Reduce(function(x, y) merge(x, y, all=TRUE), list(data2015, data2016))
data_2013_2016 <- Reduce(function(x, y) merge(x, y, all=TRUE), list(data_2013_2014, data_2015_2016))
data_2013_2017 <- Reduce(function(x, y) merge(x, y, all=TRUE), list(data_2013_2016, data2017))
data_2013_2019 <- Reduce(function(x, y) merge(x, y, all=TRUE), list(data_2013_2017, data2018, data2019))
```

```{r}
write.csv(data_2013_2019, paste("~/CNAM/Stats/Mini-memoire/data/", 'data_2013_2019_months.csv',sep = ''))
```

```{r}
data_2013_2019 <- read.csv("~/CNAM/Stats/Mini-memoire/data/data_2013_2019_months.csv")
```

```{r}
data <- data_2013_2019
```

# REPLACE NAs and RELABEL FACTORS

# SMOKING

```{r}
data$X_RFSMOK3[data$X_RFSMOK3 == 1] <- "false" # Non
data$X_RFSMOK3[data$X_RFSMOK3 == 2] <- "true" # Oui
data <- data %>% replace_with_na(replace = list(X_RFSMOK3  = c(7, 9)))


data <- data %>% replace_with_na(replace = list(X_SMOKER3  = c(9)))
data$X_SMOKER3 = cut(data$X_SMOKER3, 4, labels=c("Fumeur quotidien", "Fumeur occasionnel", "Ancien fumeur", "Non fumeur"))

data <- data %>% replace_with_na(replace = list(USENOW3  = c(7, 9)))
data$USENOW3 <- as.factor(data$USENOW3)
levels(data$USENOW3) <- c("Quotidiennement", "Occasionnellement", "Jamais")

data <- data %>% replace_with_na(replace = list(LASTSMK2  = c(77,99)))
data$LASTSMK2 = cut(data$LASTSMK2, 8, labels=c("< 1 month", '1 - 3 month',"3 - 6 months","6 - 12 months","1 - 5 year","5 - 10 years", "10 years or more", "Never smoked"))

data$STOPSMK2[data$STOPSMK2 == 1] <- "true" # Non
data$STOPSMK2[data$STOPSMK2 == 2] <- "false" # Oui
data <- data %>% replace_with_na(replace = list(STOPSMK2  = c(7,9)))

data <- data %>% replace_with_na(replace = list(SMOKDAY2 = c(7,9)))
data$SMOKDAY2 <- as.factor(data$SMOKDAY2)
levels(data$SMOKDAY2) <- c("Quotidiennement", "Occasionnellement", "Jamais")

data$SMOKE100[data$SMOKE100 == 1] <- "true" # Non
data$SMOKE100[data$SMOKE100 == 2] <- "false" # Oui
data <- data %>% replace_with_na(replace = list(SMOKE100 = c(7,9)))
```

## AGE SEXE

```{r}
data <- data %>% replace_with_na(replace = list(SEX = c(7, 9)))
data$SEX <- as.factor(data$SEX)
levels(data$SEX) <- c("Male", "Female")

data <- data %>% replace_with_na(replace = list(X_AGE65YR = c(3)))
data$X_AGEG5YR <- as.factor(data$X_AGEG5YR)
data <- data  %>% 
  mutate(X_AGEG5YR = case_when(X_AGEG5YR == 1 ~ "18 - 24",
                                    X_AGEG5YR == 2 ~ "25 - 29",
                                    X_AGEG5YR == 3 ~ "30 - 34",
                                    X_AGEG5YR == 4 ~ "35 - 39",
                                    X_AGEG5YR == 5 ~ "40 - 44",
                                    X_AGEG5YR == 6 ~ "45 - 49",
                                    X_AGEG5YR == 7 ~ "50 - 54",
                                    X_AGEG5YR == 8 ~ "55 - 59",
                                    X_AGEG5YR == 9 ~ "60 - 64",
                                    X_AGEG5YR == 10 ~ "65 - 69",
                                    X_AGEG5YR == 11 ~ "70 - 74",
                                    X_AGEG5YR == 12 ~ "75 - 79",
                                    X_AGEG5YR == 13 ~ "80 +"))

data <- data  %>% 
  mutate(X_AGE65YR = case_when(X_AGE65YR == 1 ~ "18 - 64",
                              X_AGE65YR == 2 ~ "65 +"))
data$X_AGE65YR <- as.factor(data$X_AGE65YR)

         
data$X_AGE_G <- as.factor(data$X_AGE_G)
data <- data  %>% 
  mutate(X_AGE_G = case_when(X_AGE_G == 1 ~ "18 - 24",
                             X_AGE_G == 2 ~ "25 - 34",
                             X_AGE_G == 3 ~ "35 - 44",
                             X_AGE_G == 4 ~ "45 - 54",
                             X_AGE_G == 5 ~ "55 - 64",
                             X_AGE_G == 6 ~ "65 +"))
```

## FAMILLE

```{r}
data <- data %>% replace_with_na(replace = list(MARITAL = c(9)))
data$MARITAL = cut(data$MARITAL, 6, labels=c("Marié", 'Divorcé',"Veuf","Séparé","Jamais marié","Membre d'un couple non marié"))

data$CHILDREN[data$CHILDREN == 88] <- 0
data <- data %>% replace_with_na(replace = list(CHILDREN = c(99)))
data$X_CHLDCNT = cut(data$X_CHLDCNT, 6, labels=c("Pas d'enfant", '1 enfant',"2 enfants","3 enfants","4 enfants","Plus de 5 enfants"))

data <- data %>% replace_with_na(replace = list(PREGNANT = c(7, 9)))
data$PREGNANT[data$PREGNANT == 1] <- "true" 
data$PREGNANT[data$PREGNANT == 2] <- "false" 

data <- data %>% replace_with_na(replace = list(X_CHLDCNT = c(9)))
```

## EDUCATION

```{r}
data <- data %>% replace_with_na(replace = list(EDUCA = c(9)))
data$EDUCA <- as.factor(data$EDUCA)
levels(data$EDUCA) <- c("Jamais allé à l'école", "Elementaire", "Un peu lycée", "Fini lycée", "Un peu licence", "Fini licence")

data <- data %>% replace_with_na(replace = list(X_EDUCAG = c(9)))
data$X_EDUCAG <- as.factor(data$X_EDUCAG)
levels(data$X_EDUCAG) <- c("Sans diplome", "Baccalauréat", "Ens. Sup. Sans diplome", "Ens. Sup. Avec diplome")
```

# STATUT SOCIAL

```{r}
data <- data %>% replace_with_na(replace = list(EMPLOY1 = c(9)))
data$EMPLOY1 = cut(data$EMPLOY1, 8, labels=c("Salarié", "Auto-entrepeneur","Chômeur > 1 an","Chômeur < 1 an", "Personne au foyer","Etudiant", "Retraité", "Dans l'impossibilité de travailler"))

data <- data %>% replace_with_na(replace = list(INCOME2 = c(77, 99)))
data$INCOME2 = cut(data$INCOME2, 8, labels=c("< 10 000", "10 - 15 000",'15 - 20 000',"20 - 25 000", "25 - 35 000","35 - 50 000", "50 - 75  000", "75 000 +"))

data <- data %>% replace_with_na(replace = list(X_INCOMG = c(9)))
data$X_INCOMG = cut(data$X_INCOMG, 5, labels=c("< 15 000", '15 - 25 000',"25 - 35 000","35 - 50 000","< 50 000"))

data <- data %>% replace_with_na(replace = list(RENTHOM1 = c(7, 9)))
data$RENTHOM1 = cut(data$RENTHOM1, 3, labels=c("Propriétaire", 'Locataire',"Autre"))

data <- data %>% replace_with_na(replace = list(VETERAN3 = c(7, 9)))
data$VETERAN3[data$VETERAN3 == 1] <- "true" 
data$VETERAN3[data$VETERAN3 == 2] <- "false" 
```

## SANTE MENTALE

```{r}
data$MENTHLTH[data$MENTHLTH == 88] <- 0
data <- data %>% replace_with_na(replace = list(MENTHLTH = c(77,99)))

data$POORHLTH[data$POORHLTH  == 88] <- 0
data <- data %>% replace_with_na(replace = list(POORHLTH  = c(77,99)))

data$QLMENTL2[data$QLMENTL2  == 88] <- 0
data <- data %>% replace_with_na(replace = list(QLMENTL2  = c(77,99)))

data$QLSTRES2[data$QLSTRES2  == 88] <- 0
data <- data %>% replace_with_na(replace = list(QLSTRES2  = c(77,99)))

data <- data %>% replace_with_na(replace = list(EMTSUPRT  = c(7,9)))
data$EMTSUPRT_FACTOR = as.factor(data$EMTSUPRT)
levels(data$EMTSUPRT_FACTOR)[levels(data$EMTSUPRT_FACTOR)=="1"] <- "Toujours"
levels(data$EMTSUPRT_FACTOR)[levels(data$EMTSUPRT_FACTOR)=="2"] <- "Souvent"
levels(data$EMTSUPRT_FACTOR)[levels(data$EMTSUPRT_FACTOR)=="3"] <- "Parfois"
levels(data$EMTSUPRT_FACTOR)[levels(data$EMTSUPRT_FACTOR)=="4"] <- "Rarement"
levels(data$EMTSUPRT_FACTOR)[levels(data$EMTSUPRT_FACTOR)=="5"] <- "Jamais"

data <- data %>% replace_with_na(replace = list(LSATISFY  = c(7,9)))
data$LSATISFY_FACTOR = as.factor(data$LSATISFY)
levels(data$LSATISFY_FACTOR)[levels(data$LSATISFY_FACTOR)=="1"] <- "Très satisfait"
levels(data$LSATISFY_FACTOR)[levels(data$LSATISFY_FACTOR)=="2"] <- "Satisfait"
levels(data$LSATISFY_FACTOR)[levels(data$LSATISFY_FACTOR)=="3"] <- "Insatisfait"
levels(data$LSATISFY_FACTOR)[levels(data$LSATISFY_FACTOR)=="4"] <- "Très insatisfait"

data <- data %>% replace_with_na(replace = list(ADDEPEV2  = c(7,9)))
data$ADDEPEV2[data$ADDEPEV2  == 2] <- 0
data$ADDEPEV2_FACTOR = cut(data$ADDEPEV2, 2, labels=c("false", 'true'))

```

```{r}
data$IDATE <- paste(data$IYEAR, data$IMONTH, data$IDAY, sep='-')
data$IDATE <- as.Date(data$IDATE, format="%Y-%m-%d")
```

# ORDRE COLONNES et EXPORTATION

```{r}
data <- data[, c("IDATE", "IYEAR", "IMONTH",  "X_STATE", "SEX", "X_AGEG5YR",
                  "X_AGE65YR", "X_AGE_G", "MARITAL", "PREGNANT", 
                  "NUMADULT", "CHILDREN", "X_CHLDCNT", 
                  "EDUCA", "X_EDUCAG", "EMPLOY1", 
                  "INCOME2", "X_INCOMG", "RENTHOM1", "VETERAN3", 
                  "SMOKE100","SMOKDAY2","STOPSMK2",
                  "LASTSMK2","USENOW3","X_SMOKER3", "X_RFSMOK3",
                  "POORHLTH", "MENTHLTH", "QLMENTL2", "QLSTRES2", 
                  "ADDEPEV2","EMTSUPRT", "LSATISFY")]
```

```{r}
write.csv(data, paste("~/CNAM/Stats/Mini-memoire/data/", 'data.csv',sep = ''))
```

