---
title: "R Notebook"
output: html_notebook
---



```{r}
  PMS_clean <- PMS_mean[!startsWith(PMS_mean$IDATE,"2010"),]

  PMS_new_date <- zoo(, seq(min(as.Date(PMS_mean$DATE, format = "%Y-%m-%d")), max(as.Date(PMS_mean$DATE, format = "%Y-%m-%d")), "day"))

  PMS_new_xts <- xts(PMS_clean, PMS_new_date)
  
  PMS_new <-merge(PMS_clean, PMS_new_date)
  
  ts.plot(PMS_xts)

```
```{r}
xts1 <- xts(x=1:10, order.by=Sys.Date()-1:10)
xts1


data <- rnorm(5)
dates <- seq(as.Date("2017-05-01"), length=5, by="days")
xts2 <- xts(x=data, order.by=dates)

xts3 <- xts(x=rnorm(10), order.by=as.POSIXct(Sys.Date()+1:10), born=as.POSIXct("1899-05-08"))
xts4 <- xts(x=1:10, order.by=Sys.Date()+1:10)
```

```{r}
  PMS_date2 <- as.Date(PMS_mean2$DATE, format = "%Y-%m-%d")
  PMS_cols2 <- select(PMS_mean2, SMOKE100, POORHLTH, MENTHLTH)
  
  PMS_xts2 <- xts(PMS_cols, order.by=PMS_date)
  
  zo <- zoo(, seq(min(PMS_date2), max(PMS_date2), "day"))
  
  PMS_xts3[is.na(PMS_xts3$SMOKE100),]
  
  PMS_xt4 <-na.approx(PMS_xts3, maxgap= Inf)
  plot(PMS_xt4)
```

```{r}
xts1 <- xts(x=NA, order.by=Sys.Date()-1:10)
xts1


data <- rnorm(5)
dates <- seq(as.Date("2017-05-01"), length=5, by="days")
xts2 <- xts(x=data, order.by=dates)
xts3 <- xts(x=rnorm(10), order.by=as.POSIXct(Sys.Date()+1:10), born=as.POSIXct("1899-05-08")
            xts4 <- xts(x=1:10, order.by=Sys.Date()+1:10)
```


```{r}
  PMS_date <- as.Date(PMS_mean$IDATE)
  PMS_cols <- select(PMS_mean, SMOKE100, POORHLTH, MENTHLTH)
  PMS_xts <- xts(PMS_cols, order.by=PMS_date)
  
data3 <-merge(data2, zoo(, seq(min(times.init), max(times.init), "min")))
data4 <-na.approx(data3)
  
  
  PMS_xts <- xts(PMS_mean[,2], order.by=as.Date(PMS_mean$DATE))
```


```{r}
  print(PMS_xts)
  plot(PMS_xts)
  nyears(PMS_xts)
  str(PMS_xts)
  PMS_xts <- split(PMS_xts,f="years") # split by years
  PMS_xts[1]
  plot.window(xlim=1, ylim=10)

  ts.plot(PMS_xts, col = 2:3, xlab = "Year", ylab = "Nombre de jours", main = "tobacco and mental heath")
  legend("topleft", n[2:3], lty = 1, col = 2:3, bty = "n")
```

```{r}
  xts2 <- na.approx(PMS_xts) 
  plot(xts2)

```
# scale

#### Creation de times series tpe ts

```{r}
  PMS_ts <- ts_ts(PMS_xts)
```

```{r}
  print(PMS_ts)
  plot(PMS_ts)
  colnames(PMS_ts)
  print(PMS_ts)
  str(PMS_ts)
  end(PMS_ts)
  frequency(PMS_ts)
  deltat(PMS_ts)
  plot(PMS_ts)
```

#### DIVISION EN TIMES SERIES UNIVARIES

```{r}
  smokers_ts <- smokers_mentalhealth[, 'X_RFSMOK3']
  depress_ts <- smokers_mentalhealth[, 'ADDEPEV2']
  poor_phys_mental_ts <- smokers_mentalhealth[, 'POORHLTH']
  poor_mental_ts <- smokers_mentalhealth[, 'MENTHLTH']
  ts.plot(smokers_ts)
  ts.plot(depress_ts)
  ts.plot(poor_phys_mental_ts)
  ts.plot(poor_mental_ts)
```

 <!-- Ressemble a du white noise : mean and variance constante, pas de correlations over time (pas de seasonal trends) -->
 <!-- Bemol quand meme perdiodicite cycle d'un an (du au fetes moins d'interviews)  -->

## WHITE NOISE MODEL - POOR MENTAL HEALTH

```{r}
ts.plot(poor_mental_ts)
poor_mental_ts_diff <- diff(poor_mental_ts, lag = 4) # remove long term (seasonal) trends
ts.plot(poor_mental_ts_diff)
```

Base pour d'autres modeles de time series

ARIMA(p, d, q)
- auto-regressive p
- order of integration (differencing) d
- moving average order q

#### Estimation

```{r}
arima(poor_mental_ts_diff, order=c(0, 0, 0))
```
```{r}
lapply(poor_mental_ts_diff, mean, na.rm = TRUE)
lapply(poor_mental_ts_diff, var, na.rm = TRUE)
```
> La comparaison de la moyenne et de la variance est quasi-identique


