---
title: "R Notebook"
output: html_notebook
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(scales)
library(reshape2)
library(ggplot2)
library(xts)
library(zoo)
library(tsbox)
```

```{r}
  data_1985_2019 <- read.csv("~/CNAM/Stats/Mini-memoire/data/data_1985_2019_cleaned.csv")
  data <- data_1985_2019
```

## SMOKE100, POORHLTH, MENTHLTH de 1996 a 2019

#### Choix des variables
```{r}
    PMS <- data %>%
      select(IDATE, IYEAR,  SMOKE100 , POORHLTH, MENTHLTH)
    PMS <- drop_na(PMS) # on veut qu'un individu ait repondu a toutes les questions
```

#### Aggregation par date 

```{r}
    PMS_mean <- PMS  %>%
                    filter(IYEAR != 2020) %>%
                    group_by(IDATE) %>% 
                    summarise(POORHLTH = mean(POORHLTH),
                            MENTHLTH = mean(MENTHLTH),
                            SMOKE100 = mean(SMOKE100),
                            DATE = first(IDATE))
```

#### Creation de times series type xts

- Visualisation des donnees originales
```{r}
  PMS_date <- as.Date(PMS_mean$DATE, format = "%Y-%m-%d")
  PMS_cols <- select(PMS_mean, SMOKE100, POORHLTH, MENTHLTH)
  PMS_xts <- xts(PMS_cols, order.by=PMS_date)
  plot(PMS_xts)
```

- Remplacement des donnees de 2010 par interpolation lineaire

```{r}
original_df <-PMS_mean[!startsWith(PMS_mean$IDATE,"2010"),]
times.init <- as.Date(original_df$DATE, format = "%Y-%m-%d")
new_df <-xts(original_df[,2:4],times.init)

PMS_xts_interpol <- na.approx(new_df, xout=seq(min(times.init), max(times.init), "day"))
ts.plot(PMS_xts_interpol)

PMS_ts_interpol <- ts_ts(PMS_xts_interpol)
ts_ggplot(PMS_xts_interpol, title="Evolution de la santé mentale des répondants", subtitle="Fumeurs et non fumeurs") +
  theme_tsbox() +
  scale_color_tsbox() # ts_ggplot marche aussi avec xts
```

## Visualisation multivariee

### Correlation

- POORHLTH, MENTHLTH : Nombre de jours
- SMOKE100 : 0 1

```{r}

```







