---
title: "R Notebook"
output: html_notebook
---

```{r}
    colnames(data)    

    date_index <- as.Date(data$IDATE, format = "%Y-%m-%d")

    age_cols <- data[, c("IDATE","X_AGEG5YR", "X_AGE65YR", "X_AGE_G")]

    PMS_cols <- select(PMS_mean, SMOKE100, POORHLTH, MENTHLTH)
    
    age <- age  %>%
      group_by(IDATE) %>% 
      summarise_all(mean, na.rm = TRUE)
  
    age <- xts(age, order.by=date_index)
```

## WHITE NOISE MODEL - POOR MENTAL HEALTH


```{r}
ts.plot(poor_mental_ts)
poor_mental_ts_diff <- diff(poor_mental_ts, lag = 4) # remove long term (seasonal) trends
ts.plot(poor_mental_ts_diff)
```

Base pour d'autres modeles de time series

ARIMA(p, d, q)
- auto-regressive p
- order of integration (differencing) d
- moving average order q

#### Estimation

```{r}
arima(poor_mental_ts_diff, order=c(0, 0, 0))
```

```{r}
lapply(poor_mental_ts_diff, mean, na.rm = TRUE)
lapply(poor_mental_ts_diff, var, na.rm = TRUE)
```
> La comparaison de la moyenne et de la variance est quasi-identique


