---
title: "Time series analysis of tobacco and mental health"
output: html_notebook
---

POORHLTH > 1 - 30
MENTHLTH > 1 - 30
ADDEPEV2 > yes no

```{r}
library(tidyverse)
library(scales)
library("reshape2")
library("ggplot2")
```


```{r}
data <- read.csv("~/CNAM/Stats/Mini-memoire/data/data.csv")
```


```{r}
    d <- select(data, IDATE, X_RFSMOK3, ADDEPEV2, POORHLTH, MENTHLTH)
```

```{r}
    # Creation d'une variable contenant une valeur unique
    e <- d  %>%
      mutate(X_RFSMOK3 = ifelse(X_RFSMOK3 == "true", 1, 0)) 
```

```{r}
    e <- drop_na(e)
```

```{r}
  g <- e %>%
  group_by(IDATE) %>% 
  summarize(ADDEPEV2 = sum(ADDEPEV2),
            POORHLTH = mean(POORHLTH),
            MENTHLTH = mean(MENTHLTH),
            X_RFSMOK3 = sum(X_RFSMOK3))
```

```{r}
    g$IYEAR <- as.Date(ISOdate(g$IYEAR, 1, 1))

```

```{r}
  apply( g[-1] , 2 , diff )

  i <- data.frame(diff(as.matrix(g)))
  
  g$X_RFSMOK3 <- diff(g$X_RFSMOK3)

  i <- g %>%
    mutate(X_RFSMOK3_p = diff(X_RFSMOK3))
```

```{r}
    h <- melt(g, id="IYEAR")  # convert to long format
```

















```{r}
  ggplot(h,
         aes(x=IYEAR, y=value, colour=variable)) +
    geom_line()
```







```{r}
    # Time series
    ggplot(g, aes(x=IYEAR)) +
      geom_line(aes(y = X_RFSMOK3, colour = "X_RFSMOK3")) +
      geom_line(aes(y = MENTHLTH, colour = "MENTHLTH")) 
```






```{r}
df <- data.frame(period=rep(1:4,2), 
             farm=c(rep('A',4),rep('B',4)), 
             cumVol=c(1,5,15,31,10,12,16,24), item=c(rep('Z',3),rep('Y',3),rep('X',2)),
             other = 1:8);
```



```{r}
    # Aggregation 
    f <- e %>%
      aggregate(by=list(e$IYEAR), FUN=sum) %>% 
      select(-IYEAR)
```

```{r}
ggplot(f, aes(Group.1)) + 
  geom_line(aes(y = new, colour = "new"))  + 
  geom_line(aes(y = var1, colour = "var1"))
```


```{r}
ggplot(test_data, aes(date)) + 
  geom_line(aes(y = var0, colour = "var0")) + 
  geom_line(aes(y = var1, colour = "var1"))
```


```{r}
  test_data <-
    data.frame(
      var0 = 100 + c(0, cumsum(runif(49, -20, 20))),
      var1 = 150 + c(0, cumsum(runif(49, -10, 10))),
      date = seq(as.Date("2002-01-01"), by="1 month", length.out=100)
    )
```

```{r}
library("reshape2")
library("ggplot2")

test_data_long <- melt(test_data, id="date")  # convert to long format

ggplot(data=test_data_long,
       aes(x=date, y=value, colour=variable)) +
  geom_line()

```


```{r}
ggplot(f, aes(x = Group.1, y=new)) + 
  geom_line()
```